baseURL = "/victorious-hartford"
languageCode = "en"
defaultContentLanguage = "en"
title = "Victorious Hartford"
theme = "stip-hugo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "Victorious Hartford"
    bio = "A Strategic Vision"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:info@victorious-hartford.us"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/dancingfrog/victorious-hartford"

